package views;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class PlayerViewController {
	@FXML
	private Button playStopButton;
	@FXML
	private Button undoPauseButton;
	@FXML
	private Button redoRestartButton;
	@FXML
	private Button saveButton;
	@FXML
	private Button loadButton;

	// Event Listener on Button[#playStopButton].onAction
	@FXML
	public void playStopButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#undoPauseButton].onAction
	@FXML
	public void undoPauseButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#redoRestartButton].onAction
	@FXML
	public void redoRestartButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#loadButton].onAction
	@FXML
	public void loadButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
